i3: Switch bitwarden to AppImage for now
`bitwarden-desktop` (installed via pacman) fails with:

```
App threw an error during load
Error: /usr/lib/bitwarden/app.asar.unpacked/node_modules/@bitwarden/desktop-napi/desktop_napi.node: undefined symbol: sqlite3_step
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2617)
    at Module._extensions..node (node:internal/modules/cjs/loader:1873:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2844)
    at Module.load (node:internal/modules/cjs/loader:1448:32)
    at Module._load (node:internal/modules/cjs/loader:1270:12)
    at c._load (node:electron/js2c/node_init:2:18041)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16)
```

The AppImage auto-updates itself and writes the new AppImage into the
same folder. Since its filename contains the version number, we need to
glob.